---
downloads: ~/.ansible-downloads/

configure_terminal: false

# Set to 'true' to configure the Dock via dockutil.
configure_dock: true
dockitems_remove:
  - "App Store"
  - Calendar
  - Contacts
  - FaceTime
  - Keynote
  - Launchpad
  - Mail
  - Maps
  - Music
  - Notes
  - Numbers
  - Pages
  - Photos
  - Podcasts
  - TV

dockitems_persist:
  - name: "Google Chrome"
    path: "/Applications/Google Chrome.app/"
    pos: 1
  - name: "iTerm"
    path: "/Applications/iTerm.app/"
    pos: 2
  - name: "Sublime Text"
    path: "/Applications/Sublime%20Text.app/"
    pos: 3
  - name: "Slack"
    path: "/Applications/Slack.app/"
    pos: 4
  - name: "Visual Studio Code"
    path: "/Applications/Visual%20Studio%20Code.app/"
    pos: 5
  - name: "System Preferences"
    path: "/System/Applications/System%20Preferences.app/"
    pos: 6
  - name: "Authy Desktop"
    path: "/Applications/Authy%20Desktop.app/"
    pos: 7
  - name: "WhatsApp"
    path: "/Applications/WhatsApp.app/"
    pos: 8
  - name: "Signal"
    path: "/Applications/Signal.app/"
    pos: 9
  - name: "Telegram"
    path: "/Applications/Telegram.app/"
    pos: 10
  - name: "Miro"
    path: "/Applications/Miro.app/"
    pos: 11

configure_sudoers: false
sudoers_custom_config: ""
# Example:
# sudoers_custom_config: |
#   # Allow users in admin group to use sudo with no password.
#   %admin ALL=(ALL) NOPASSWD: ALL

# Set to 'true' to install dotfiles
configure_dotfiles: true
dotfiles_repo: https://github.com/bartdorlandt/dotfiles.git
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: ~/git/dotfiles
dotfiles_repo_version: master
dotfiles_files:
  # - .bash_profile
  # - .bashrc
  - .screenrc
  - .shell_aliases
  - .tmux.conf
  - .vimrc
  - .vimrc.bundles
  - .zshrc

homebrew_installed_packages:
  - bat
  - coreutils
  - fd
  - fzf
  - gh
  - git
  - gnupg
  - go
  - htop
  - httpie
  - jq
  - mtr
  - openssh
  - prettyping
  - pwgen
  - pyenv
  - ripgrep
  # - sipcalc
  - tailscale
  - telnet
  - tmate
  - tmux
  - wget
  - whois
  - xping
  - zsh-autosuggestions
  - zsh-syntax-highlighting
  # - git-lfs
  # - irrtoolset
  # - neovim
  # - node
  # - pinentry-mac

homebrew_taps:
  - homebrew/cask
  - homebrew/cask-drivers
  - homebrew/cask-fonts
  - homebrew/core
  - martintopholm/xping

homebrew_cask_accept_external_apps: true
homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - docker
  - drawio
  - dropbox
  - firefox
  - google-chrome
  - google-drive
  - iterm2
  - karabiner-elements
  - logi-options-plus
  - miro
  - qview
  - rectangle
  - signal
  - slack
  - sublime-text
  - telegram
  - visual-studio-code
  - whatsapp
  - wireshark
  - yubico-yubikey-manager
  - zoom
  # - font-hack-nerd-font
  # - google-earth-pro
  # - logitech-camera-settings
  # - serial

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps:
  - { id: 409203825, name: "Numbers" }
mas_uninstalled_apps:
  - { id: 408981434, name: "iMovie" }
  - { id: 682658836, name: "GarageBand" }
mas_email: ""
mas_password: ""

# Set to 'true' to configure osx defaults
configure_osx: false
osx_script: "~/.osx --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
# - name: drush
#   state: present # present/absent, default: present
#   version: "^8.1" # default: N/A
gem_packages: []
# - name: bundler
#   state: present # present/absent/latest, default: present
#   version: "~> 1.15.1" # default: N/A
npm_packages: []
# - name: webpack
#   state: present # present/absent/latest, default: present
#   version: "^2.6" # default: N/A
# pip_packages: []
# - name: mkdocs
#   state: present # present/absent/latest, default: present
#   version: "0.16.3" # default: N/A
pip_packages:
  # - name: git-cu
  #   state: latest
  - name: ansible
    state: latest
  - name: ansible-lint
    state: latest

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: "{{ playbook_dir }}/../tasks/*.yml"

# Pyenv config
# # Latest Python versions
# pyenv_python38_version: "3.8.13"
# pyenv_python39_version: "3.9.13"
pyenv_python310_version: "3.10.5"

# Python versions to install
pyenv_python_versions:
  # - "{{ pyenv_python38_version }}"
  # - "{{ pyenv_python39_version }}"
  - "{{ pyenv_python310_version }}"

# Set global pyenv version
pyenv_global: "{{ pyenv_python310_version }}"

user_group: staff

sublime_base_path: "~/Library/Application Support/Sublime Text"
sublime_config_path: "Packages/User"
