---
OS_mac: true

configure_terminal: false

# Set to 'true' to configure the Dock via dockutil.
configure_dock: true
dockitems_remove:
  - "App Store"
  - Calendar
  - Contacts
  - FaceTime
  - Keynote
  - Launchpad
  - Mail
  - Maps
  - Messages
  - Music
  - News
  - Notes
  - Numbers
  - Pages
  - Photos
  - Podcasts
  - Safari
  - TV

dockitems_persist:
  - name: "Google Chrome"
    path: "/Applications/Google Chrome.app/"
    pos: 1
  - name: "iTerm"
    path: "/Applications/iTerm.app/"
    pos: 2
  - name: "Sublime Text"
    path: "/Applications/Sublime Text.app/"
    pos: 3
  - name: "Slack"
    path: "/Applications/Slack.app/"
    pos: 4
  - name: "Visual Studio Code"
    path: "/Applications/Visual Studio Code.app/"
    pos: 5
  - name: "Notion"
    path: "/Applications/Notion.app/"
    pos: 6
  - name: "Authy Desktop"
    path: "/Applications/Authy Desktop.app/"
    pos: 7
  - name: "WhatsApp"
    path: "/Applications/WhatsApp.app/"
    pos: 8
  - name: "Signal"
    path: "/Applications/Signal.app/"
    pos: 9
  - name: "Telegram"
    path: "/Applications/Telegram.app/"
    pos: 10
  - name: "System Settings"
    path: "/System/Applications/System Settings.app/"
    pos: 11

homebrew_installed_packages:
  - bat
  - coreutils
  - docker
  - fd
  - fzf
  - gh
  - git
  - gnupg
  - go
  - htop
  - httpie
  - iproute2mac
  - jq
  - mtr
  - openssh
  - podman
  - prettyping
  - pwgen
  - ripgrep
  - tailscale
  - telnet
  - tmate
  - tmux
  - tree
  - wget
  - whois
  - xping

homebrew_taps:
  - homebrew/cask
  - homebrew/cask-drivers
  - homebrew/cask-fonts
  - homebrew/core
  - martintopholm/xping

homebrew_cask_accept_external_apps: true
homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - authy
  - clipy
  - docker
  - drawio
  - dropbox
  - firefox
  - github
  - google-chrome
  - google-drive
  - iterm2
  - karabiner-elements
  - keepassx
  - logi-options-plus
  - notion
  - rectangle
  - podman-desktop
  - signal
  - slack
  - sublime-text
  - telegram
  - virtualbox
  - virtualbox-extension-pack
  - visual-studio-code
  - whatsapp
  - wireshark
  - yubico-yubikey-manager
  - zoom

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps:
  - { id: 409203825, name: "Numbers" }
# mas_uninstalled_apps:
#   - { id: 408981434, name: "iMovie" }
#   - { id: 682658836, name: "GarageBand" }
mas_email: ""
mas_password: ""

# Set to 'true' to configure osx defaults
configure_osx: false
osx_script: "~/.osx --no-restart"

user_group: staff

sublime_base_path: "~/Library/Application Support/Sublime Text"
sublime_config_path: "Packages/User"
