---
OS_ubuntu: false
OS_mac: false

downloads: ~/.ansible-downloads/

configure_sudoers: false
sudoers_custom_config: ""
# Example:
# sudoers_custom_config: |
#   # Allow users in admin group to use sudo with no password.
#   %admin ALL=(ALL) NOPASSWD: ALL

# Set to 'true' to install dotfiles
configure_dotfiles: true
dotfiles_repo: https://github.com/bartdorlandt/dotfiles.git
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: ~/git/dotfiles
dotfiles_repo_version: master
dotfiles_files:
  # - .bash_profile
  # - .bashrc
  - .screenrc
  - .shell_aliases
  - .tmux.conf
  - .vimrc
  - .vimrc.bundles
  - .zshrc

# Glob pattern to ansible task files to run after all other tasks are finished.
# post_provision_tasks: "{{ playbook_dir }}/../tasks/*.yml"

# Pyenv config
# # Latest Python versions
# pyenv_python38_version: "3.8.13"
# pyenv_python39_version: "3.9.13"
pyenv_python310_version: "3.10.6"

# Python versions to install
pyenv_python_versions:
  # - "{{ pyenv_python38_version }}"
  # - "{{ pyenv_python39_version }}"
  - "{{ pyenv_python310_version }}"

# Set global pyenv version
pyenv_global: "{{ pyenv_python310_version }}"

pip_packages:
  - name: ansible
    state: latest
  - name: ansible-lint
    state: latest
#
# git_repos:
# - {repo: $url, path: $dest_folder}

git_init_default_branch: master
git_pull_rebase: false
