---
OS_ubuntu: true

# Need to check
sublime_base_path: "~/.config/Sublime Text"
sublime_config_path: "Packages/User"

# Docker
install_docker: true

packages:
  - autofs
  - bat
  - bzip2
  - curl
  - dkms
  - git
  - google-chrome-stable
  - gnome-tweaks
  - gparted
  - htop
  - insync
  - insync-nautilus
  - iotop
  - jq
  - nfs-common
  - nmap
  - postfix
  - remmina
  - ripgrep
  - scdaemon
  - signal-desktop
  - sni-qt
  - sublime-text
  - tcpdump
  - tilix
  - tmux
  - traceroute
  - tree
  - unattended-upgrades
  - unrar
  - vim-nox
  - virtualbox
  - vlc
  - whois
  - xournal
  - zsh

# Homebrew packages to be installed
brew_formulae: []
# Homebrew git repo
# homebrew_git_repo: "https://github.com/Homebrew/brew"
# Homebrew release (default is the master github repo)
# homebrew_release: "master"
# Homebrew user
# homebrew_user: "{{ lookup('env', 'USER') }}"

vscode_install: true
