---
- hosts: all
  connection: local

  pre_tasks:
    - include_vars: config.yml
      tags: ['always']

- import_playbook: geerlingguy.mac-dev-playbook/main.yml

- hosts: all
  connection: local
  roles:
    - role: osx-defaults
      tags: ['osx-defaults']
