---
- name: Laptop setup playbook
  hosts: all
  connection: local

  pre_tasks:
    - name: Include variables
      ansible.builtin.include_vars: config.yml
      tags: always
    - name: OS specific variables
      ansible.builtin.include_vars: "{{ playbook_dir }}/config.{{ ansible_distribution | lower }}.yml"
      tags: always
    - name: Include env.yml variables
      ansible.builtin.include_vars: .env.yml
      tags: always

  tasks:
    - name: Git setup
      import_tasks: tasks/git-setup.yml
      tags: git

    - name: MAC OS tasks
      when: OS_mac
      block:
        - name: Include the hombrew role
          ansible.builtin.include_role:
            name: geerlingguy.mac.homebrew
          tags: homebrew
        - name: Other MAC software
          ansible.builtin.include_role:
            name: geerlingguy.mac.mas
          when: mas_installed_apps or mas_installed_app_ids
          tags: mas
        - name: Other MAC software
          ansible.builtin.include_role:
            name: geerlingguy.mac.dock
          when: configure_dock
          tags: dock
        - name: OSX defaults
          ansible.builtin.include_role:
            name: osx-defaults
          tags: osx-defaults
        - name: App iClouddrive
          import_tasks: tasks/iclouddrive.mac.yml
          tags: "iclouddrive"
        - name: App iTerm2
          import_tasks: tasks/iterm2.mac.yml
          tags: "iterm2"
        - name: App karabiner
          import_tasks: tasks/karabiner.mac.yml
          tags: "karabiner"

    - name: Ubuntu OS tasks
      when: OS_ubuntu
      block:
        - name: Install apt sources
          import_tasks: tasks/vscode.ubuntu.yml
          tags: vscode
          when: vscode_install
        - name: Install docker
          ansible.builtin.include_role:
            name: geerlingguy.docker
          vars:
            docker_users: ["{{ ansible_env.USER }}"]
          tags: docker
          when: install_docker
        - name: Include the hombrew role
          ansible.builtin.include_role:
            name: monolithprojects.homebrew
          tags: homebrew
        - name: Install packages # noqa package-latest
          ansible.builtin.apt:
            package: packages
            state: latest
          tags: packages
          when: packages

    # System independent tasks
    - name: Set up dirs and files
      import_tasks: tasks/forward.yml
      tags: filemod

    - name: Dotfiles
      ansible.builtin.include_role:
        name: geerlingguy.dotfiles
      tags: dotfiles
      when: configure_dotfiles

    - import_tasks: tasks/git-repos.yml
      tags: git-repos
    - import_tasks: tasks/ohmyzsh.yml
      tags: ohmyzsh
    - import_tasks: tasks/python.yml
      tags: python
    - import_tasks: tasks/sublime-text.yml
      tags: sublime-text
