---
- name: Git repos
  ansible.builtin.git:
    repo: "{{ item.repo }}"
    dest: "{{ item.path }}"
    update: true
    accept_hostkey: true
  loop: "{{ git_repos }}"
  when: git_repos is defined
  tags: git
