---
- name: Make sure the karabiner dirs exist
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.config/karabiner"
    state: directory
    mode: "700"
  tags: karabiner

- name: Karabiner profile symbolic link
  ansible.builtin.file:
    src: "{{ playbook_dir }}/tasks/files/{{ item }}"
    dest: "~/.config/karabiner/{{ item }}"
    owner: "{{ ansible_env.USER }}"
    group: "{{ user_group }}"
    state: link
  loop:
    - karabiner.json
  tags: karabiner
