---
- name: Make sure the karabiner dirs exist
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.config/karabiner"
    state: directory
    mode: "700"

- name: Karabiner profile
  ansible.builtin.file:
    src: "{{ playbook_dir }}/tasks/files/{{ item }}"
    dest: "~/.config/karabiner/{{ item }}"
    owner: "{{ ansible_env.USER }}"
    group: "{{ user_group }}"
    state: "file"
    mode: 0644
  loop:
    - karabiner.json
