---
- name: Ensure Oh My ZSH repo exists # noqa latest[git]
  ansible.builtin.git:
    repo: "https://github.com/ohmyzsh/ohmyzsh.git"
    dest: ~/.oh-my-zsh
    depth: 1
    update: false

- name: Git pull zsh-autosuggestions # noqa latest[git]
  ansible.builtin.git:
    repo: https://github.com/zsh-users/zsh-autosuggestions.git
    dest: "{{ ansible_env.HOME }}/.oh-my-zsh/custom/plugins/zsh-autosuggestions"
    depth: 1
    update: true

- name: Git pull zsh-syntax-highlighting # noqa latest[git]
  ansible.builtin.git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
    dest: "{{ ansible_env.HOME }}/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting"
    depth: 1
    update: true

- name: Create the .zshrc_local
  when: ohmyzsh_plugins is defined
  block:
    - name: Ensure the .zshrc_local file exists
      ansible.builtin.file:
        path: "{{ ansible_env.HOME }}/.zshrc_local"
        state: touch
        mode: 0600
        modification_time: preserve
        access_time: preserve

    - name: Fill the .zshrc_local
      ansible.builtin.blockinfile:
        path: "{{ ansible_env.HOME }}/.zshrc_local"
        block: |
          plugins=({{ ohmyzsh_plugins }})

# starship
- name: Create the starship.toml
#  when: ohmyzsh_plugins is defined
  block:
    - name: Ensure the ~/.config/starship.toml file exists
      ansible.builtin.file:
        path: "{{ ansible_env.HOME }}/.config/starship.toml"
        state: touch
        mode: 0600
        modification_time: preserve
        access_time: preserve

    - name: Fill the starship.toml
      ansible.builtin.blockinfile:
        path: "{{ ansible_env.HOME }}/.config/starship.toml"
        block: |
          {{ starship_config }}
