---
- name: Restart MenuBar # noqa ignore-errars
  ansible.builtin.command: killall SystemUIServer
  failed_when: false

- name: Restart Dock # noqa ignore-errars
  ansible.builtin.command: killall Dock
  failed_when: false

- name: Restart Finder # noqa ignore-errars
  ansible.builtin.command: killall Finder
  failed_when: false
